import ReduxProvider from '@/redux/provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/Sidebar'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Sidebar />
          <div className='ml-[200px]'>
            <Header />
            <div className='p-8 mt-9'>
              {children}
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  )
}
